


/**********************************************************************************/
/*** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE PANICKAPPS API GENERATOR ***/

/*                It is HIGHLY suggested that you do not edit this file.          */

//  DATABASE:     panayiota_easybusiness
//  FILE:         routecustomer.java
//  TABLE:        routecustomer
//  DATETIME:     2018-02-10 12:04:41pm
//  DESCRIPTION:  N/A

/**********************************************************************************/

package eb_managementapp.Entities;

import java.io.Serializable;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;


public class Routecustomer implements Serializable {


	//-------------------- Supporting Finals --------------------

	final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
	final SimpleDateFormat TIME_FORMAT = new SimpleDateFormat("HH:mm:ss");
	final SimpleDateFormat TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");


	//-------------------- Attributes --------------------

    private int ID;
    private int RouteID;
    private int CustomerID;

	//-------------------- Constructor --------------------

    public Routecustomer(
		int ID, 
		int RouteID, 
		int CustomerID
		) {
        this.ID = ID;
		this.RouteID = RouteID;
		this.CustomerID = CustomerID;
    }

	//-------------------- Getter Methods --------------------

	/**
     * @return int
     */
     public int getID() { return this.ID; }

	/**
     * @return int
     */
     public int getRouteID() { return this.RouteID; }

	/**
     * @return int
     */
     public int getCustomerID() { return this.CustomerID; }


	//-------------------- Setter Methods --------------------

	/**
     * @param value int(11)
     */
     public void setRouteID(int value) { this.RouteID = value; }

	/**
     * @param value int(11)
     */
     public void setCustomerID(int value) { this.CustomerID = value; }


	//-------------------- JSON Generation Methods --------------------

    /**
     * Specifies how objects of this class should be converted to JSON format.
     * @return String
     */
    public String toJSON() {
        return "\r\n{\r\n\t\"ID\": " + this.ID + ",\r\n\t\"RouteID\": " + this.RouteID + ",\r\n\t\"CustomerID\": " + this.CustomerID + "\r\n}";
    }
    
    /**
     * Converts an array of Routecustomer objects to a JSON Array.
     * @param routecustomer_array
     * @return String
     */
    public static String toJSONArray(Routecustomer [] routecustomer_array) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routecustomer i : routecustomer_array) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an ArrayList of Routecustomer objects to a JSON Array.
     * @param routecustomer_arraylist ArrayList of Routecustomer to convert to JSON.
     * @return String
     */
    public static String toJSONArray(ArrayList<Routecustomer> routecustomer_arraylist) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routecustomer i : routecustomer_arraylist) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an Vector of Routecustomer objects to a JSON Array.
     * @param routecustomer_vector Vector of Routecustomer to convert to JSON.
     * @return String
     */
    public static String toJSONArray(Vector<Routecustomer> routecustomer_vector) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routecustomer i : routecustomer_vector) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts a List of Routecustomer objects to a JSON Array.
     * @param routecustomer_list List of Routecustomer to convert to JSON.
     * @return String
     */
    public static String toJSONArray(List<Routecustomer> routecustomer_list) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routecustomer i : routecustomer_list) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    @Override
    public String toString() {
        return toJSON();
    }

}

