


/**********************************************************************************/
/*** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE PANICKAPPS API GENERATOR ***/

/*                It is HIGHLY suggested that you do not edit this file.          */

//  DATABASE:     panayiota_easybusiness
//  FILE:         routes.java
//  TABLE:        routes
//  DATETIME:     2018-02-10 12:04:41pm
//  DESCRIPTION:  N/A

/**********************************************************************************/

package eb_managementapp.Entities;

import java.io.Serializable;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;


public class Routes implements Serializable {


	//-------------------- Supporting Finals --------------------

	final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
	final SimpleDateFormat TIME_FORMAT = new SimpleDateFormat("HH:mm:ss");
	final SimpleDateFormat TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");


	//-------------------- Attributes --------------------

    private int ID;
    private String Name;
    private int RouteCustomersID;
    private int DayID;

	//-------------------- Constructor --------------------

    public Routes(
		int ID, 
		String Name, 
		int RouteCustomersID, 
		int DayID
		) {
        this.ID = ID;
		this.Name = Name;
		this.RouteCustomersID = RouteCustomersID;
		this.DayID = DayID;
    }

	//-------------------- Getter Methods --------------------

	/**
     * @return int
     */
     public int getID() { return this.ID; }

	/**
     * @return String
     */
     public String getName() { return this.Name; }

	/**
     * @return int
     */
     public int getRouteCustomersID() { return this.RouteCustomersID; }

	/**
     * @return int
     */
     public int getDayID() { return this.DayID; }


	//-------------------- Setter Methods --------------------

	/**
     * @param value varchar(255)
     */
     public void setName(String value) { this.Name = value; }

	/**
     * @param value int(11)
     */
     public void setRouteCustomersID(int value) { this.RouteCustomersID = value; }

	/**
     * @param value int(11)
     */
     public void setDayID(int value) { this.DayID = value; }


	//-------------------- JSON Generation Methods --------------------

    /**
     * Specifies how objects of this class should be converted to JSON format.
     * @return String
     */
    public String toJSON() {
        return "\r\n{\r\n\t\"ID\": " + this.ID + ",\r\n\t\"Name\": \"" + this.Name+ "\",\r\n\t\"RouteCustomersID\": " + this.RouteCustomersID + ",\r\n\t\"DayID\": " + this.DayID + "\r\n}";
    }
    
    /**
     * Converts an array of Routes objects to a JSON Array.
     * @param routes_array
     * @return String
     */
    public static String toJSONArray(Routes [] routes_array) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routes i : routes_array) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an ArrayList of Routes objects to a JSON Array.
     * @param routes_arraylist ArrayList of Routes to convert to JSON.
     * @return String
     */
    public static String toJSONArray(ArrayList<Routes> routes_arraylist) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routes i : routes_arraylist) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an Vector of Routes objects to a JSON Array.
     * @param routes_vector Vector of Routes to convert to JSON.
     * @return String
     */
    public static String toJSONArray(Vector<Routes> routes_vector) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routes i : routes_vector) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts a List of Routes objects to a JSON Array.
     * @param routes_list List of Routes to convert to JSON.
     * @return String
     */
    public static String toJSONArray(List<Routes> routes_list) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Routes i : routes_list) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    @Override
    public String toString() {
        return toJSON();
    }

}

