


/**********************************************************************************/
/*** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE PANICKAPPS API GENERATOR ***/

/*                It is HIGHLY suggested that you do not edit this file.          */

//  DATABASE:     panayiota_easybusiness
//  FILE:         suppliers.java
//  TABLE:        suppliers
//  DATETIME:     2018-02-10 12:04:41pm
//  DESCRIPTION:  N/A

/**********************************************************************************/

package eb_managementapp.Entities;

import java.io.Serializable;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;


public class Suppliers implements Serializable {


	//-------------------- Supporting Finals --------------------

	final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
	final SimpleDateFormat TIME_FORMAT = new SimpleDateFormat("HH:mm:ss");
	final SimpleDateFormat TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");


	//-------------------- Attributes --------------------

    private int ID;
    private String Name;
    private int CountryID;
    private String Address;
    private String Telephone;
    private String City;

	//-------------------- Constructor --------------------

    public Suppliers(
		int ID, 
		String Name, 
		int CountryID, 
		String Address, 
		String Telephone, 
		String City
		) {
        this.ID = ID;
		this.Name = Name;
		this.CountryID = CountryID;
		this.Address = Address;
		this.Telephone = Telephone;
		this.City = City;
    }

	//-------------------- Getter Methods --------------------

	/**
     * @return int
     */
     public int getID() { return this.ID; }

	/**
     * @return String
     */
     public String getName() { return this.Name; }

	/**
     * @return int
     */
     public int getCountryID() { return this.CountryID; }

	/**
     * @return String
     */
     public String getAddress() { return this.Address; }

	/**
     * @return String
     */
     public String getTelephone() { return this.Telephone; }

	/**
     * @return String
     */
     public String getCity() { return this.City; }


	//-------------------- Setter Methods --------------------

	/**
     * @param value varchar(255)
     */
     public void setName(String value) { this.Name = value; }

	/**
     * @param value int(11)
     */
     public void setCountryID(int value) { this.CountryID = value; }

	/**
     * @param value varchar(255)
     */
     public void setAddress(String value) { this.Address = value; }

	/**
     * @param value varchar(255)
     */
     public void setTelephone(String value) { this.Telephone = value; }

	/**
     * @param value varchar(255)
     */
     public void setCity(String value) { this.City = value; }


	//-------------------- JSON Generation Methods --------------------

    /**
     * Specifies how objects of this class should be converted to JSON format.
     * @return String
     */
    public String toJSON() {
        return "\r\n{\r\n\t\"ID\": " + this.ID + ",\r\n\t\"Name\": \"" + this.Name+ "\",\r\n\t\"CountryID\": " + this.CountryID + ",\r\n\t\"Address\": \"" + this.Address+ "\",\r\n\t\"Telephone\": \"" + this.Telephone+ "\",\r\n\t\"City\": \"" + this.City+ "\"\r\n}";
    }
    
    /**
     * Converts an array of Suppliers objects to a JSON Array.
     * @param suppliers_array
     * @return String
     */
    public static String toJSONArray(Suppliers [] suppliers_array) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Suppliers i : suppliers_array) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an ArrayList of Suppliers objects to a JSON Array.
     * @param suppliers_arraylist ArrayList of Suppliers to convert to JSON.
     * @return String
     */
    public static String toJSONArray(ArrayList<Suppliers> suppliers_arraylist) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Suppliers i : suppliers_arraylist) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an Vector of Suppliers objects to a JSON Array.
     * @param suppliers_vector Vector of Suppliers to convert to JSON.
     * @return String
     */
    public static String toJSONArray(Vector<Suppliers> suppliers_vector) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Suppliers i : suppliers_vector) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts a List of Suppliers objects to a JSON Array.
     * @param suppliers_list List of Suppliers to convert to JSON.
     * @return String
     */
    public static String toJSONArray(List<Suppliers> suppliers_list) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Suppliers i : suppliers_list) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    @Override
    public String toString() {
        return toJSON();
    }

}

