


/**********************************************************************************/
/*** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE PANICKAPPS API GENERATOR ***/

/*                It is HIGHLY suggested that you do not edit this file.          */

//  DATABASE:     panayiota_easybusiness
//  FILE:         supplytransactions.java
//  TABLE:        supplytransactions
//  DATETIME:     2018-02-10 12:04:41pm
//  DESCRIPTION:  N/A

/**********************************************************************************/

package com.easybusiness.eb_androidapp.Entities;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;


public class SupplyTransactions implements Serializable {


    //-------------------- Supporting Finals --------------------

    final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
    final SimpleDateFormat TIME_FORMAT = new SimpleDateFormat("HH:mm:ss");
    final SimpleDateFormat TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");


    //-------------------- Attributes --------------------

    private int ID;
    private int SupplierSuppliesID;
    private int DateMade;
    private int Quantity;

    //-------------------- Constructor --------------------

    public SupplyTransactions(
            int ID,
            int SupplierSuppliesID,
            int DateMade,
            int Quantity
    ) {
        this.ID = ID;
        this.SupplierSuppliesID = SupplierSuppliesID;
        this.DateMade = DateMade;
        this.Quantity = Quantity;
    }

    //-------------------- Getter Methods --------------------

    /**
     * @return int
     */
    public int getID() { return this.ID; }

    /**
     * @return int
     */
    public int getSupplierSuppliesID() { return this.SupplierSuppliesID; }

    /**
     * @return int
     */
    public int getDateMade() { return this.DateMade; }

    /**
     * @return int
     */
    public int getQuantity() { return this.Quantity; }


    //-------------------- Setter Methods --------------------

    /**
     * @param value int(11)
     */
    public void setSupplierSuppliesID(int value) { this.SupplierSuppliesID = value; }

    /**
     * @param value int(13)
     */
    public void setDateMade(int value) { this.DateMade = value; }

    /**
     * @param value int(11)
     */
    public void setQuantity(int value) { this.Quantity = value; }


    //-------------------- JSON Generation Methods --------------------

    /**
     * Specifies how objects of this class should be converted to JSON format.
     * @return String
     */
    public String toJSON() {
        return "\r\n{\r\n\t\"ID\": " + this.ID + ",\r\n\t\"SupplierSuppliesID\": " + this.SupplierSuppliesID + ",\r\n\t\"DateMade\": " + this.DateMade + ",\r\n\t\"Quantity\": " + this.Quantity + "\r\n}";
    }

    /**
     * Converts an array of SupplyTransactions objects to a JSON Array.
     * @param supplyTransactions_array
     * @return String
     */
    public static String toJSONArray(SupplyTransactions[] supplyTransactions_array) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final SupplyTransactions i : supplyTransactions_array) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }

    /**
     * Converts an ArrayList of SupplyTransactions objects to a JSON Array.
     * @param supplyTransactions_arraylist ArrayList of SupplyTransactions to convert to JSON.
     * @return String
     */
    public static String toJSONArray(ArrayList<SupplyTransactions> supplyTransactions_arraylist) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final SupplyTransactions i : supplyTransactions_arraylist) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }

    /**
     * Converts an Vector of SupplyTransactions objects to a JSON Array.
     * @param supplyTransactions_vector Vector of SupplyTransactions to convert to JSON.
     * @return String
     */
    public static String toJSONArray(Vector<SupplyTransactions> supplyTransactions_vector) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final SupplyTransactions i : supplyTransactions_vector) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }

    /**
     * Converts a List of SupplyTransactions objects to a JSON Array.
     * @param supplyTransactions_list List of SupplyTransactions to convert to JSON.
     * @return String
     */
    public static String toJSONArray(List<SupplyTransactions> supplyTransactions_list) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final SupplyTransactions i : supplyTransactions_list) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }

    @Override
    public String toString() {
        return toJSON();
    }

}

