


/**********************************************************************************/
/*** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE PANICKAPPS API GENERATOR ***/

/*                It is HIGHLY suggested that you do not edit this file.          */

//  DATABASE:     panayiota_easybusiness
//  FILE:         unittypes.java
//  TABLE:        unittypes
//  DATETIME:     2018-02-10 12:04:41pm
//  DESCRIPTION:  N/A

/**********************************************************************************/

package com.easybusiness.eb_androidapp.Entities;

import java.io.Serializable;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;


public class Unittypes implements Serializable {


	//-------------------- Supporting Finals --------------------

	final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
	final SimpleDateFormat TIME_FORMAT = new SimpleDateFormat("HH:mm:ss");
	final SimpleDateFormat TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");


	//-------------------- Attributes --------------------

    private int ID;
    private String Name;

	//-------------------- Constructor --------------------

    public Unittypes(
		int ID, 
		String Name
		) {
        this.ID = ID;
		this.Name = Name;
    }

	//-------------------- Getter Methods --------------------

	/**
     * @return int
     */
     public int getID() { return this.ID; }

	/**
     * @return String
     */
     public String getName() { return this.Name; }


	//-------------------- Setter Methods --------------------

	/**
     * @param value varchar(255)
     */
     public void setName(String value) { this.Name = value; }


	//-------------------- JSON Generation Methods --------------------

    /**
     * Specifies how objects of this class should be converted to JSON format.
     * @return String
     */
    public String toJSON() {
        return "\r\n{\r\n\t\"ID\": " + this.ID + ",\r\n\t\"Name\": \"" + this.Name+ "\"\r\n}";
    }
    
    /**
     * Converts an array of Unittypes objects to a JSON Array.
     * @param unittypes_array
     * @return String
     */
    public static String toJSONArray(Unittypes [] unittypes_array) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Unittypes i : unittypes_array) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an ArrayList of Unittypes objects to a JSON Array.
     * @param unittypes_arraylist ArrayList of Unittypes to convert to JSON.
     * @return String
     */
    public static String toJSONArray(ArrayList<Unittypes> unittypes_arraylist) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Unittypes i : unittypes_arraylist) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an Vector of Unittypes objects to a JSON Array.
     * @param unittypes_vector Vector of Unittypes to convert to JSON.
     * @return String
     */
    public static String toJSONArray(Vector<Unittypes> unittypes_vector) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Unittypes i : unittypes_vector) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts a List of Unittypes objects to a JSON Array.
     * @param unittypes_list List of Unittypes to convert to JSON.
     * @return String
     */
    public static String toJSONArray(List<Unittypes> unittypes_list) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Unittypes i : unittypes_list) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    @Override
    public String toString() {
        return toJSON();
    }

}

