


/**********************************************************************************/
/*** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE PANICKAPPS API GENERATOR ***/

/*                It is HIGHLY suggested that you do not edit this file.          */

//  DATABASE:     panayiota_easybusiness
//  FILE:         userlevels.java
//  TABLE:        userlevels
//  DATETIME:     2018-02-10 12:04:41pm
//  DESCRIPTION:  N/A

/**********************************************************************************/

package com.easybusiness.eb_androidapp.Entities;

import java.io.Serializable;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;


public class Userlevels implements Serializable {


	//-------------------- Supporting Finals --------------------

	final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
	final SimpleDateFormat TIME_FORMAT = new SimpleDateFormat("HH:mm:ss");
	final SimpleDateFormat TIMESTAMP_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");


	//-------------------- Attributes --------------------

    private int UserLevelID;
    private String UserLevelName;
    private boolean Show;

	//-------------------- Constructor --------------------

    public Userlevels(
		int UserLevelID, 
		String UserLevelName, 
		boolean Show
		) {
        this.UserLevelID = UserLevelID;
		this.UserLevelName = UserLevelName;
		this.Show = Show;
    }

	//-------------------- Getter Methods --------------------

	/**
     * @return int
     */
     public int getUserLevelID() { return this.UserLevelID; }

	/**
     * @return String
     */
     public String getUserLevelName() { return this.UserLevelName; }

	/**
     * @return boolean
     */
     public boolean getShow() { return this.Show; }


	//-------------------- Setter Methods --------------------

	/**
     * @param value varchar(255)
     */
     public void setUserLevelName(String value) { this.UserLevelName = value; }

	/**
     * @param value tinyint(1)
     */
     public void setShow(boolean value) { this.Show = value; }


	//-------------------- JSON Generation Methods --------------------

    /**
     * Specifies how objects of this class should be converted to JSON format.
     * @return String
     */
    public String toJSON() {
        return "\r\n{\r\n\t\"UserLevelID\": " + this.UserLevelID + ",\r\n\t\"UserLevelName\": \"" + this.UserLevelName+ "\",\r\n\t\"Show\": " + this.Show + "\r\n}";
    }
    
    /**
     * Converts an array of Userlevels objects to a JSON Array.
     * @param userlevels_array
     * @return String
     */
    public static String toJSONArray(Userlevels [] userlevels_array) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Userlevels i : userlevels_array) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an ArrayList of Userlevels objects to a JSON Array.
     * @param userlevels_arraylist ArrayList of Userlevels to convert to JSON.
     * @return String
     */
    public static String toJSONArray(ArrayList<Userlevels> userlevels_arraylist) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Userlevels i : userlevels_arraylist) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts an Vector of Userlevels objects to a JSON Array.
     * @param userlevels_vector Vector of Userlevels to convert to JSON.
     * @return String
     */
    public static String toJSONArray(Vector<Userlevels> userlevels_vector) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Userlevels i : userlevels_vector) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    /**
     * Converts a List of Userlevels objects to a JSON Array.
     * @param userlevels_list List of Userlevels to convert to JSON.
     * @return String
     */
    public static String toJSONArray(List<Userlevels> userlevels_list) {
        StringBuilder strArray = new StringBuilder("[ ");
        for (final Userlevels i : userlevels_list) {
            strArray.append(i.toJSON());
            strArray.append(", ");
        }
        strArray = new StringBuilder(strArray.substring(0, strArray.length() - 3));
        strArray.append("} ] ");
        return strArray.toString();
    }
    
    @Override
    public String toString() {
        return toJSON();
    }

}

