/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eb_managementapp.UI.Forms;

import eb_managementapp.DB.ConnectionCreator;
import static eb_managementapp.EB_ManagementApp.addProductTypeForm;
import static eb_managementapp.EB_ManagementApp.addProductsForm;
import static eb_managementapp.EB_ManagementApp.addSizeForm;
import static eb_managementapp.EB_ManagementApp.setUpForm;
import eb_managementapp.UI.Components.CheckboxGroup;
import eb_managementapp.UI.Components.JTableUtilities;
import java.awt.Point;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

public class AddProductsForm extends javax.swing.JFrame {

    final String TITLE = "Easy Business - Add Products";

    public AddProductsForm() {
        initComponents();

        //---
        //setLayout(new GridLayout(0, 2));
        CheckboxGroup group = new CheckboxGroup(new String[]{"150ml", "250ml", "300ml", "350ml", "500ml", "1L", "2L","3L"});

        group.setBounds(new Rectangle(new Point(85, 110), group.getPreferredSize()));
        ProductPanel.add(group);
        pack();
        setLocationRelativeTo(null);

        try {

            //SELECT From ProductType
            ConnectionCreator connectionCreator = new ConnectionCreator();
            Connection connection = connectionCreator.connect();

            Statement getProductsTypeStatement = connection.createStatement();
            String qr = " Select ProductTypeName From ProductTypes";
            ResultSet rs;
            rs = getProductsTypeStatement.executeQuery(qr);

            TypeComboBox.removeAllItems();
            // iterate through the java resultset
            while (rs.next()) {
                String typeName = rs.getString("ProductTypeName");
                TypeComboBox.addItem(typeName);

                // print the results
                //System.out.println("Name" + typeName);
            }
            getProductsTypeStatement.close();

        } catch (SQLException ex) {
            Logger.getLogger(AddProductsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        //---
        setTitle(TITLE);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductPanel = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        AddTypeButton = new javax.swing.JButton();
        ProductNameLabel = new javax.swing.JLabel();
        ProductNameTextField = new javax.swing.JTextField();
        SizeLabel = new javax.swing.JLabel();
        AddSizeButton = new javax.swing.JButton();
        QuantityLabel = new javax.swing.JLabel();
        QuantitySpinner = new javax.swing.JSpinner();
        PriceLabel = new javax.swing.JLabel();
        PriceTextField = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        AddNewProductButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        TablePanel = new javax.swing.JPanel();
        productsScrollPane = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        ViewProductsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProductPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        TypeLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TypeLabel.setText("Type:");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select" }));
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        AddTypeButton.setText("Add Type");
        AddTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTypeButtonActionPerformed(evt);
            }
        });

        ProductNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ProductNameLabel.setText("Name:");

        ProductNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameTextFieldActionPerformed(evt);
            }
        });

        SizeLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SizeLabel.setText("Size:");

        AddSizeButton.setText("Add Size");
        AddSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSizeButtonActionPerformed(evt);
            }
        });

        QuantityLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        QuantityLabel.setText("Quantity:");

        PriceLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        PriceLabel.setText("Price:");

        PriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addComponent(QuantityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(TypeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SizeLabel)
                                            .addComponent(ProductNameLabel))
                                        .addGap(11, 11, 11)
                                        .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddTypeButton)))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                        .addComponent(AddSizeButton)
                        .addContainerGap())))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeLabel)
                            .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductNameLabel)
                            .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(SizeLabel))
                    .addComponent(AddTypeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddSizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityLabel)
                    .addComponent(QuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceLabel)
                    .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        AddNewProductButton.setText("Add New Product");
        AddNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewProductButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddNewProductButton)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(AddNewProductButton))
                .addGap(35, 35, 35))
        );

        TablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List of Products", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        productsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        productsTable.setAutoscrolls(false);
        productsTable.getTableHeader().setReorderingAllowed(false);
        productsScrollPane.setViewportView(productsTable);

        ViewProductsButton.setText("View Products");
        ViewProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewProductsButton)
                .addContainerGap())
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(productsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewProductsButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        setVisible(false);
        setUpForm = new SetUpForm();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ProductNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameTextFieldActionPerformed

    private void PriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTextFieldActionPerformed

    private void AddNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewProductButtonActionPerformed

        ConnectionCreator connectionCreator = new ConnectionCreator();
        Connection connection = connectionCreator.connect();

        String queryInsertProducts = " insert into Products (ProductID,CompanyID,ProductSizeID,Name,Quantity, Price)"
                + "values (3,4,5,'" + ProductNameTextField.getText() + "','" + QuantitySpinner.getValue() + "','" + PriceTextField.getText() + "')";

        try {
            //Create insert preparedstatement for administrator
            PreparedStatement prepareProductStatement = connection.prepareStatement(queryInsertProducts);
            prepareProductStatement.execute();

            showMessageDialog(null, "Product Added -->" + ProductNameTextField.getText());

        } catch (SQLException ex) {
            Logger.getLogger(AddProductsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        setVisible(true);
        addProductsForm = new AddProductsForm();
    }//GEN-LAST:event_AddNewProductButtonActionPerformed

    private void ViewProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsButtonActionPerformed

        Vector<String> productNumbers = new Vector<>();
        Vector<String> productNames = new Vector<>();
        Vector<String> productSize = new Vector<>();
        Vector<String> productPrice = new Vector<>();
        Vector<String> productQuantity = new Vector<>();
        Vector<String> columnNames = new Vector<>();
        columnNames.add("#");
        columnNames.add("Name");
        columnNames.add("Size");
        columnNames.add("Price");
        columnNames.add("Quantity");
        Vector<Vector<String>> data = new Vector<>();

        try {
            //SELECT From ProductType
            ConnectionCreator connectionCreator = new ConnectionCreator();
            Connection connection = connectionCreator.connect();

            Statement getProductsListStatement = connection.createStatement();
            String query = " Select * From Products,ProductSizes Where Products.ProductSizeID=ProductSizes.ProductSizeID";
            ResultSet rs;
            rs = getProductsListStatement.executeQuery(query);
            Integer i = 0;

            while (rs.next()) {
                i++;
                productNumbers.add(i.toString());
                productNames.add(rs.getString("Name"));
                productSize.add(rs.getString("ProductSizeName"));
                productPrice.add(rs.getString("Price"));
                productQuantity.add(rs.getString("Quantity"));

            }
            getProductsListStatement.close();
        } catch (SQLException ex) {
            Logger.getLogger(AddProductsForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < productNumbers.size(); i++) {
            Vector<String> row = new Vector<>();
            row.add(productNumbers.get(i));
            row.add(productNames.get(i));
            row.add(productSize.get(i));
            row.add(productPrice.get(i));
            row.add(productQuantity.get(i));
            data.add(row);
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        productsTable.setModel(model);

        JTableUtilities.setJTableColumnsWidth(productsTable, productsTable.getWidth(), 10, 40, 20, 15, 15);

//        
//        TableColumnModel columnModel =  productsTable.getColumnModel();
//        columnModel.getColumn(0).setPreferredWidth(50);
        // this.productTable.setListData(productNames);

    }//GEN-LAST:event_ViewProductsButtonActionPerformed

    private void AddSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSizeButtonActionPerformed
        setVisible(true);
        addSizeForm = new AddSizeForm();
    }//GEN-LAST:event_AddSizeButtonActionPerformed

    private void AddTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTypeButtonActionPerformed
        setVisible(true);
        addProductTypeForm = new AddProductTypeForm();
    }//GEN-LAST:event_AddTypeButtonActionPerformed

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed

        //TODO Panayiota: Action when selecting an item in TypeComboBox.

    }//GEN-LAST:event_TypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewProductButton;
    private javax.swing.JButton AddSizeButton;
    private javax.swing.JButton AddTypeButton;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JLabel QuantityLabel;
    private javax.swing.JSpinner QuantitySpinner;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JButton ViewProductsButton;
    private javax.swing.JScrollPane productsScrollPane;
    private javax.swing.JTable productsTable;
    // End of variables declaration//GEN-END:variables
}
