package eb_managementapp.UI.Forms;

import eb_managementapp.DB.ConnectionCreator;
import eb_managementapp.UI.Forms.SetUpForm;
import static eb_managementapp.EB_ManagementApp.setUpForm;
import eb_managementapp.UI.Components.AlertBox;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import static javax.swing.JOptionPane.showMessageDialog;

public class AddUsersForm extends javax.swing.JFrame {

    final String TITLE = "Add Employees";

    /**
     * Creates new form AddUsersForm
     */
    public AddUsersForm() {
        initComponents();

        //COUNTRIES SELECTION COMBOBOX
        try {
            //Select Statment to choose countries
            ConnectionCreator connectionCreator = new ConnectionCreator();
            Connection connection = connectionCreator.connect();

            Statement getCountryStatement = connection.createStatement();
            String qr = " Select Name From Countries";
            ResultSet rs = getCountryStatement.executeQuery(qr);

            countryComboBox.removeAllItems();
            // iterate through the java resultset
            while (rs.next()) {
                String typeName = rs.getString("Name");
                countryComboBox.addItem(typeName);
            }
            getCountryStatement.close();

        } catch (SQLException ex) {
            Logger.getLogger(AddUsersForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        setTitle(TITLE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        employeeDetailsPanel = new javax.swing.JPanel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeNameTextField = new javax.swing.JTextField();
        employeeLastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        employeeTelephoneLabel = new javax.swing.JLabel();
        employeeTelephoneTextField = new javax.swing.JTextField();
        employeeAddressLabel = new javax.swing.JLabel();
        employeeAddressTextField = new javax.swing.JTextField();
        employeeCityLabel = new javax.swing.JLabel();
        employeeCityTextField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox<>();
        EmploymentDetailsPanel = new javax.swing.JPanel();
        positionLabel = new javax.swing.JLabel();
        positionCompoBox = new javax.swing.JComboBox<>();
        hireDateLabel = new javax.swing.JLabel();
        dateOfHirePicker = new org.jdesktop.swingx.JXDatePicker();
        FullTimeRadioButton = new javax.swing.JRadioButton();
        PartTimeRadioButton = new javax.swing.JRadioButton();
        AddNewEmployeesButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        viewEmployeesPanel = new javax.swing.JPanel();
        viewEmployeesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Business - Add Employees");

        employeeDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        employeeNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        employeeNameLabel.setText("Name:");

        employeeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNameTextFieldActionPerformed(evt);
            }
        });

        employeeLastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        employeeLastNameLabel.setText("Last Name:");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        usernameLabel.setText("UserName: ");

        employeeTelephoneLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        employeeTelephoneLabel.setText("Telephone:");

        employeeTelephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTelephoneTextFieldActionPerformed(evt);
            }
        });

        employeeAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        employeeAddressLabel.setText("Address:");

        employeeAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeAddressTextFieldActionPerformed(evt);
            }
        });

        employeeCityLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        employeeCityLabel.setText("City:");

        employeeCityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeCityTextFieldActionPerformed(evt);
            }
        });

        countryLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        countryLabel.setText("Country:");

        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout employeeDetailsPanelLayout = new javax.swing.GroupLayout(employeeDetailsPanel);
        employeeDetailsPanel.setLayout(employeeDetailsPanelLayout);
        employeeDetailsPanelLayout.setHorizontalGroup(
            employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(employeeNameLabel)
                            .addComponent(employeeLastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(employeeNameTextField)))
                    .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(employeeTelephoneLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(employeeTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(usernameLabel)
                                .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(employeeAddressLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(employeeAddressTextField)))
                            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(employeeCityLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(countryLabel)
                                        .addGap(10, 10, 10)))
                                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(countryComboBox, 0, 175, Short.MAX_VALUE)
                                    .addComponent(employeeCityTextField))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeeDetailsPanelLayout.setVerticalGroup(
            employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDetailsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLastNameLabel))
                .addGap(11, 11, 11)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeTelephoneLabel)
                    .addComponent(employeeTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeAddressLabel)
                    .addComponent(employeeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeCityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(employeeDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(countryLabel)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EmploymentDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employment  Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        positionLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        positionLabel.setText("Position:");

        positionCompoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        positionCompoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCompoBoxActionPerformed(evt);
            }
        });

        hireDateLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        hireDateLabel.setText("Hire Date:");

        dateOfHirePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfHirePickerActionPerformed(evt);
            }
        });

        buttonGroup.add(FullTimeRadioButton);
        FullTimeRadioButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        FullTimeRadioButton.setText("Full Time");

        buttonGroup.add(PartTimeRadioButton);
        PartTimeRadioButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        PartTimeRadioButton.setText("Part Time");
        PartTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartTimeRadioButtonActionPerformed(evt);
            }
        });

        AddNewEmployeesButton.setText("Add New Emplyees");
        AddNewEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewEmployeesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmploymentDetailsPanelLayout = new javax.swing.GroupLayout(EmploymentDetailsPanel);
        EmploymentDetailsPanel.setLayout(EmploymentDetailsPanelLayout);
        EmploymentDetailsPanelLayout.setHorizontalGroup(
            EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(AddNewEmployeesButton))
                    .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                        .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(positionLabel))
                            .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hireDateLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FullTimeRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PartTimeRadioButton))
                            .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateOfHirePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(positionCompoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        EmploymentDetailsPanelLayout.setVerticalGroup(
            EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmploymentDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionCompoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hireDateLabel)
                    .addComponent(dateOfHirePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(EmploymentDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullTimeRadioButton)
                    .addComponent(PartTimeRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddNewEmployeesButton)
                .addGap(11, 11, 11))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next ->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addGap(11, 11, 11))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewEmployeesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List of Employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        viewEmployeesButton.setText("View Employees");
        viewEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewEmployeesPanelLayout = new javax.swing.GroupLayout(viewEmployeesPanel);
        viewEmployeesPanel.setLayout(viewEmployeesPanelLayout);
        viewEmployeesPanelLayout.setHorizontalGroup(
            viewEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewEmployeesPanelLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(viewEmployeesButton)
                .addContainerGap())
        );
        viewEmployeesPanelLayout.setVerticalGroup(
            viewEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewEmployeesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewEmployeesButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmploymentDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewEmployeesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmploymentDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewEmployeesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void employeeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void employeeTelephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTelephoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeTelephoneTextFieldActionPerformed

    private void employeeCityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeCityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeCityTextFieldActionPerformed

    private void employeeAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeAddressTextFieldActionPerformed

    private void dateOfHirePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfHirePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfHirePickerActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void viewEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeesButtonActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_viewEmployeesButtonActionPerformed

    private void PartTimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartTimeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartTimeRadioButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed

    private void positionCompoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCompoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionCompoBoxActionPerformed

    private void AddNewEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewEmployeesButtonActionPerformed
        try {

            //Combine the first letter of the first name with the last name:
            char firstNameFirstLetter = employeeNameTextField.getText().charAt(0);      //e.g Panayiota  --> P
            String lastName = lastNameTextField.getText();                              //e.g Michaelides --> Michaelides
            String username = firstNameFirstLetter + lastName;                          //Result = PMichaelides

            boolean exists = true;

            ConnectionCreator connectionCreator = new ConnectionCreator();
            Connection connection = connectionCreator.connect();

            int counter = -1;

            while (exists) {
                counter++;
                Statement statement = connection.createStatement();
                String query = "";
                if (counter == 0) {
                    query = "SELECT Username FROM Users WHERE LOWER(Username) = '" + username.toLowerCase() + "'";
                } else {
                    query = "SELECT Username FROM Users WHERE LOWER(Username) = '" + username.toLowerCase() + counter + "'";
                }
                System.out.println(query);
                ResultSet rs = statement.executeQuery(query);
                if (!rs.next()) {
                    exists = false;
                    if (counter != 0) {
                        username += counter;
                    }
                }
                statement.close();
            }

            //rs = statement.executeQuery(query);
            //Not unique
            Statement insertStatement = connection.createStatement();
            String insertQuery = "INSERT INTO Users (Username, Password, UserTypeID, FirstName, LastName, DateHired, City, Address, Telephone, CountryID) "
                    + "VALUES ("
                    + "'" + username.toLowerCase() + "',"
                    + "'',"
                    + "1,"
                    + "'" + employeeNameTextField.getText() + "',"
                    + "'" + lastNameTextField.getText() + "',"
                    + dateOfHirePicker.getDate().getTime() + ","
                    + "'" + employeeCityTextField.getText() + "',"
                    + "'" + employeeAddressTextField.getText() + "',"
                    + "'" + employeeTelephoneTextField.getText() + "',"
                    + countryComboBox.getSelectedIndex()+1
                    + "); ";
            int statusInsert = insertStatement.executeUpdate(insertQuery);
            if (statusInsert > 0) {
                //TODO: Show alert box? "User was added"
            }
            else {
                //TODO: Show alert box? "Couldnt add user"
            }
            insertStatement.close();

        } catch (SQLException ex) {
            Logger.getLogger(AddProductsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddNewEmployeesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewEmployeesButton;
    private javax.swing.JPanel EmploymentDetailsPanel;
    private javax.swing.JRadioButton FullTimeRadioButton;
    private javax.swing.JRadioButton PartTimeRadioButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> countryComboBox;
    private javax.swing.JLabel countryLabel;
    private org.jdesktop.swingx.JXDatePicker dateOfHirePicker;
    private javax.swing.JLabel employeeAddressLabel;
    private javax.swing.JTextField employeeAddressTextField;
    private javax.swing.JLabel employeeCityLabel;
    private javax.swing.JTextField employeeCityTextField;
    private javax.swing.JPanel employeeDetailsPanel;
    private javax.swing.JLabel employeeLastNameLabel;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JTextField employeeNameTextField;
    private javax.swing.JLabel employeeTelephoneLabel;
    private javax.swing.JTextField employeeTelephoneTextField;
    private javax.swing.JLabel hireDateLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox<String> positionCompoBox;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton viewEmployeesButton;
    private javax.swing.JPanel viewEmployeesPanel;
    // End of variables declaration//GEN-END:variables
}
