/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eb_managementapp.UI.Forms;

import Utilities.HTTPConnection;
import eb_managementapp.DB.ConnectionCreator;
import static eb_managementapp.EB_ManagementApp.setUpForm;
import eb_managementapp.Entities.Countries;
import eb_managementapp.Entities.Customerproducts;
import eb_managementapp.Entities.Customers;
import eb_managementapp.Entities.Products;
import eb_managementapp.Entities.Suppliersupplies;
import eb_managementapp.Entities.Supplies;
import eb_managementapp.UI.Components.CheckboxGroup;
import eb_managementapp.UI.Components.JTableUtilities;
import java.awt.Point;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

public class CustomersForm extends javax.swing.JFrame {

//    Vector<String> customerNumbers;
//    Vector<String> customerNames;
//    Vector<String> customerProducts;
//    Vector<String> columnNames;
    private ArrayList<Customers> customersList;
    private ArrayList<Countries> countriesList;
    private ArrayList<Customerproducts> customerProductsList;
    private ArrayList<Products> productsList;

    CheckboxGroup productsGroup;

    public CustomersForm() {
        initComponents();

        String[] sizeNamesArray = new String[1];

//            //DefaultSizes List
//            String qr2 = " Select Name From Products";
//            ResultSet rs2;
//            rs2 = getProductsStatement.executeQuery(qr2);
//
//            Vector<String> productNames = new Vector<>();
//            // iterate through the java resultset
//            while (rs2.next()) {
//                productNames.add(rs2.getString("Name"));
//            }
//            getProductsStatement.close();
//
//            //copy all elements from sizeNames (Vector) to sizeNamesArray(Array)
//            sizeNamesArray = new String[productNames.size()];
//            for (int i = 0; i < sizeNamesArray.length; i++) {
//                sizeNamesArray[i] = productNames.get(i);
//            }
//
//        } catch (SQLException ex) {
//            Logger.getLogger(AddProductsForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        CheckboxGroup group = new CheckboxGroup(sizeNamesArray);
//
//        group.setBounds(new Rectangle(new Point(110, 240), group.getPreferredSize()));
//        customerPanel.add(group);
        pack();
        setLocationRelativeTo(null);

        getProducts();
        getCountries();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerPanel = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        customerTelephoneLabel = new javax.swing.JLabel();
        customerTelephoneTextField = new javax.swing.JTextField();
        customerAddressLabel = new javax.swing.JLabel();
        customerAddressTextField = new javax.swing.JTextField();
        customerCityLabel = new javax.swing.JLabel();
        customerCityTextField = new javax.swing.JTextField();
        customerCountryLabel = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox<>();
        suppliesList = new javax.swing.JLabel();
        addNewCustomertButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        customerListPanel = new javax.swing.JPanel();
        customerScrollPanel = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        viewCustomersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customerNameLabel.setText("Customer Name:");

        customerNameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        customerTelephoneLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customerTelephoneLabel.setText("Telephone:");

        customerTelephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerTelephoneTextFieldActionPerformed(evt);
            }
        });

        customerAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customerAddressLabel.setText("Address:");

        customerAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAddressTextFieldActionPerformed(evt);
            }
        });

        customerCityLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customerCityLabel.setText("City:");

        customerCityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCityTextFieldActionPerformed(evt);
            }
        });

        customerCountryLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        customerCountryLabel.setText("Country:");

        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });

        suppliesList.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        suppliesList.setText("Products:");

        addNewCustomertButton.setText("Add Customer");
        addNewCustomertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCustomertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                        .addComponent(customerCityLabel)
                                        .addGap(11, 11, 11))
                                    .addGroup(customerPanelLayout.createSequentialGroup()
                                        .addComponent(customerNameLabel)
                                        .addGap(5, 5, 5)))
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(customerPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(customerCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(customerPanelLayout.createSequentialGroup()
                                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(customerTelephoneLabel)
                                            .addComponent(customerAddressLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(customerAddressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(customerTelephoneTextField)))
                                    .addGroup(customerPanelLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(customerCountryLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(suppliesList)
                                .addGap(172, 172, 172)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addNewCustomertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerTelephoneLabel))
                .addGap(11, 11, 11)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerCountryLabel))
                .addGap(18, 18, 18)
                .addComponent(suppliesList, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(addNewCustomertButton)
                .addContainerGap())
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next ->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        customerScrollPanel.setViewportView(customerTable);

        viewCustomersButton.setText("View Customers");
        viewCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerListPanelLayout = new javax.swing.GroupLayout(customerListPanel);
        customerListPanel.setLayout(customerListPanelLayout);
        customerListPanelLayout.setHorizontalGroup(
            customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerListPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewCustomersButton)))
                .addContainerGap())
        );
        customerListPanelLayout.setVerticalGroup(
            customerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerListPanelLayout.createSequentialGroup()
                .addComponent(customerScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCustomersButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        setUpForm = new SetUpForm();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addNewCustomertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCustomertButtonActionPerformed
        addCustomer();
    }//GEN-LAST:event_addNewCustomertButtonActionPerformed

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryComboBoxActionPerformed

    private void customerAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerAddressTextFieldActionPerformed

    private void customerTelephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerTelephoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTelephoneTextFieldActionPerformed

    private void customerCityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerCityTextFieldActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        setVisible(false);
        setUpForm = new SetUpForm();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void viewCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersButtonActionPerformed
        getCustomerProducts();
    }//GEN-LAST:event_viewCustomersButtonActionPerformed

    private void addCustomer() {

        //Get field values:
        String name = customerNameTextField.getText().toString();
        String city = customerCityTextField.getText().toString();
        String address = customerAddressTextField.getText().toString();
        String telephone = customerTelephoneTextField.getText().toString();
        int countryID = countriesList.get(countryComboBox.getSelectedIndex()).getID();
        ArrayList<Integer> customerProductIDs = new ArrayList();

        //Make the call:
        String addCustomersJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Customers", "Create",
                "SessionID=aa&ID=1&Name=" + name + "&CountryID=" + countryID + "&Address=" + address + "&Telephone=" + telephone + "&City=" + city + "&CustomerProductsID=0"
        );

        //Get last customer's ID
        String getCustomersSizeJSON = HTTPConnection.executePost("http://panickapps.com/eb/API/", "Customers", "GetMaxID", "");
        int lastCustomerID = -1;
        try {
             lastCustomerID = Integer.parseInt(getCustomersSizeJSON);

        } catch (Exception e) {
            e.printStackTrace();
        }

        //Get Selected Products
        List<JCheckBox> checkBoxes = productsGroup.getCheckBoxes();
        for (int i = 1; i < checkBoxes.size(); i++) {

            if (checkBoxes.get(i).isSelected()) {
                customerProductIDs.add(productsList.get(i - 1).getID());
            }

        }
        

        //Add Each Product to Customer Products for this customer
        for(int i = 0; i<customerProductIDs.size(); i++){
            String currentProductJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Customerproducts", "Create", "ID=1&SessionID=aa&ProductID=" + customerProductIDs.get(i) + "&CustomerID=" + lastCustomerID);
            System.out.println(currentProductJSON);
            
        }
        
        //Get Last CustomerProducts ID 
        int lastCustomerProductsID=-1;
        String getCustomerProductsJSON = HTTPConnection.executePost("http://panickapps.com/eb/API/", "Customerproducts", "GetMaxID", "");

        try {
            lastCustomerProductsID = Integer.parseInt(getCustomerProductsJSON);

        } catch (Exception e) {
            e.printStackTrace();
        }
        //Get customerProduct
        
        System.out.println("Nicos: " + lastCustomerProductsID);
        
        int pCustomerID = -1;
        int pProductID = -1;
        String getPJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Customerproducts", "GetByID", "SessionID=aa&ID=" + lastCustomerProductsID);
        try {
            JSONObject jsonObject = new JSONObject(getPJSON);
            System.out.println(getPJSON);
            pCustomerID = jsonObject.getInt("CustomerID");
            pProductID = jsonObject.getInt("ProductID");

        } catch (Exception e) {
            e.printStackTrace();
        }
       
        //Update the customerProductsID
        String updatedJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Customerproducts", "Update", "SessionID=aa&ID=" + lastCustomerProductsID + "&ProductID=" + pProductID + "&CustomerID=" + pCustomerID );
        
        try {
            JSONObject jsonObject = new JSONObject(addCustomersJSON);
            final String status = jsonObject.getString("Status");
            final String title = jsonObject.getString("Title");
            final String message = jsonObject.getString("Message");

            showMessageDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);

            if (status.equals(HTTPConnection.RESPONSE_ERROR)) {
                System.out.println("Fail " + addCustomersJSON);
            } else if (status.equals(HTTPConnection.RESPONSE_OK)) {
                //Reset fields:
                setVisible(true);
                countryComboBox.setSelectedIndex(0);
                customerNameTextField.setText("");
                customerCityTextField.setText("");
                customerAddressTextField.setText("");
                customerTelephoneTextField.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        getCustomers();
    }

    public void getCustomers() {
        customersList = new ArrayList<>();
        getCountries();

        //Get customers from api
        String customersJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Customers", "GetMultiple", "Limit=2&SessionID=aa");
        try {
            JSONObject jsonObject = new JSONObject(customersJSON);
            final String status = jsonObject.getString("Status");
            final String title = jsonObject.getString("Title");
            final String message = jsonObject.getString("Message");

            if (status.equals(HTTPConnection.RESPONSE_OK)) {
                JSONArray dataArray = jsonObject.getJSONArray("Data");
                for (int i = 0; i < dataArray.length(); i++) {
                    JSONObject currentItem = dataArray.getJSONObject(i);

                    int id = currentItem.getInt("ID");
                    String name = currentItem.getString("Name");
                    int countryID = currentItem.getInt("CountryID");
                    String city = currentItem.getString("City");
                    String telephone = currentItem.getString("Telephone");
                    String address = currentItem.getString("Address");
                    int customerProductsID = currentItem.getInt("CustomerProductsID");

                    Customers customer = new Customers(id, name, countryID, city, telephone, address, customerProductsID);
                    customersList.add(customer);
                }
            } else {
                showMessageDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);
                System.out.println("Fail " + customersJSON);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getProducts() {
        productsList = new ArrayList<>();

        //Get customers from api
        String productsJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Products", "GetMultiple", "SessionID=aa");
        try {
            JSONObject jsonObject = new JSONObject(productsJSON);
            final String status = jsonObject.getString("Status");
            final String title = jsonObject.getString("Title");
            final String message = jsonObject.getString("Message");

            if (status.equals(HTTPConnection.RESPONSE_OK)) {
                JSONArray dataArray = jsonObject.getJSONArray("Data");
                for (int i = 0; i < dataArray.length(); i++) {
                    JSONObject currentItem = dataArray.getJSONObject(i);

                    int id = currentItem.getInt("ID");
                    String name = currentItem.getString("Name");
                    float price = currentItem.getFloat("Price");
                    int quantity = currentItem.getInt("QuantityInStock");
                    int productSizeID = currentItem.getInt("ProductSizeID");
                    int productTypeID = currentItem.getInt("ProductTypeID");
                    int productSuppliesID = currentItem.getInt("ProductSuppliesID");

                    Products c = new Products(id, name, price, quantity, productSizeID, productTypeID, productSuppliesID);
                    productsList.add(c);
                }
            } else {
                showMessageDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);
                System.out.println("Fail " + productsJSON);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String[] productNames = new String[productsList.size()];
        for (int i = 0; i < productsList.size(); i++) {
            productNames[i] = productsList.get(i).getName();
        }
        productsGroup = new CheckboxGroup(productNames);

        productsGroup.setBounds(new Rectangle(new Point(110, 240), productsGroup.getPreferredSize()));
        customerPanel.add(productsGroup);

    }

    public void getCustomerProducts() {
        customerProductsList = new ArrayList<>();
        getProducts();
        getCustomers();

        //Get customers from api
        String customerProductsJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Customerproducts", "GetMultiple", "Limit=2&SessionID=aa");
        try {
            JSONObject jsonObject = new JSONObject(customerProductsJSON);
            final String status = jsonObject.getString("Status");
            final String title = jsonObject.getString("Title");
            final String message = jsonObject.getString("Message");

            if (status.equals(HTTPConnection.RESPONSE_OK)) {
                JSONArray dataArray = jsonObject.getJSONArray("Data");
                for (int i = 0; i < dataArray.length(); i++) {
                    JSONObject currentItem = dataArray.getJSONObject(i);

                    int id = currentItem.getInt("ID");
                    int customerID = currentItem.getInt("CustomerID");
                    int productsID = currentItem.getInt("ProductID");

                    Customerproducts customerProducts = new Customerproducts(id, customerID, productsID);
                    customerProductsList.add(customerProducts);
                }
            } else {
                showMessageDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);
                System.out.println("Fail " + customerProductsJSON);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //Create a new model for the table:
        DefaultTableModel customersProductsTableModel = new DefaultTableModel();

        //Add the table columns:
        customersProductsTableModel.addColumn("ID");
        customersProductsTableModel.addColumn("Customer");
        customersProductsTableModel.addColumn("Product");

        //Add each item in the list as a row in the table:
        for (int i = 0; i < customerProductsList.size(); i++) {
            //Put Customers Name in the Table
            String customerName = "";
            for (int j = 0; j < customersList.size(); j++) {
                if (customersList.get(j).getID() == customerProductsList.get(i).getCustomerID()) {
                    customerName = customersList.get(j).getName();
                }
            }
            //Put Products Name in the Table
            String productName = "";
            for (int j = 0; j < productsList.size(); j++) {
                if (productsList.get(j).getID() == customerProductsList.get(i).getProductID()) {
                    productName = productsList.get(j).getName();
                }
            }

            Object[] currentRow = {
                customerProductsList.get(i).getID(),
                customerName,
                productName
            };
            customersProductsTableModel.addRow(currentRow);
        }
        customerTable.setModel(customersProductsTableModel);

    }

    public void getCountries() {
        countriesList = new ArrayList<>();
        countryComboBox.removeAllItems();

        //Get customers from api
        String countriesJSON = HTTPConnection.executePost(HTTPConnection.API_URL, "Countries", "GetMultiple", "");
        try {
            JSONObject jsonObject = new JSONObject(countriesJSON);
            final String status = jsonObject.getString("Status");
            final String title = jsonObject.getString("Title");
            final String message = jsonObject.getString("Message");

            if (status.equals(HTTPConnection.RESPONSE_OK)) {
                JSONArray dataArray = jsonObject.getJSONArray("Data");
                for (int i = 0; i < dataArray.length(); i++) {
                    JSONObject currentItem = dataArray.getJSONObject(i);

                    int id = currentItem.getInt("ID");
                    String name = currentItem.getString("Name");

                    Countries c = new Countries(id, name);
                    countriesList.add(c);
                }
            } else {
                showMessageDialog(null, message, title, JOptionPane.PLAIN_MESSAGE);
                System.out.println("Fail " + countriesJSON);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        for (int i = 0; i < countriesList.size(); i++) {
            countryComboBox.addItem(countriesList.get(i).getName());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewCustomertButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> countryComboBox;
    private javax.swing.JLabel customerAddressLabel;
    private javax.swing.JTextField customerAddressTextField;
    private javax.swing.JLabel customerCityLabel;
    private javax.swing.JTextField customerCityTextField;
    private javax.swing.JLabel customerCountryLabel;
    private javax.swing.JPanel customerListPanel;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JScrollPane customerScrollPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel customerTelephoneLabel;
    private javax.swing.JTextField customerTelephoneTextField;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel suppliesList;
    private javax.swing.JButton viewCustomersButton;
    // End of variables declaration//GEN-END:variables
}
